#!/bin/bash

function checkDepends(){
	if ! which mplayer > /dev/null || ! which identify > /dev/null ;then
		echo "No dependencies installed on system. PLS install Mplayer and ImageMagick"
		exit 2
	fi
}

function getDateFromIMG(){
	local fulldate=`identify -verbose $1 | grep DateTimeOriginal`
	fdate=`echo $fulldate | awk '{print $2}' | tr ':' '-' | cut -c 3-99` 
	ftime=`echo $fulldate | awk '{print $3}' | tr ':' '-'`
	fextension=`echo ${1##*.} | tr A-Z a-z`
}

function getDateFromMOV(){
	local exifdata=`mplayer -really-quiet -identify -frames 0 -vo null -nosound -nolirc $1 | grep -A 1 creation_time | tail -1 | cut -d '=' -f 2`
	fdate=`echo $exifdata | cut -d "T" -f 1 | cut -c 3-99` 
	ftime=`echo $exifdata | cut -d "T" -f 2 | cut -d '.' -f 1 |  tr ':' '-'`
	fextension=`echo ${1##*.} | tr A-Z a-z`
}

function copyOrMove(){
	if [ $save == 0 ]; then
		mv --backup=t -v $1 $fdate\ $ftime\ $suffix.$fextension
	else
		cp --backup=t -vp $1 $fdate\ $ftime\ $suffix.$fextension
	fi
}

function checkDiff(){
	for i in ${EXISTINGARRAY[*]}; do
		diff $1 $i &> /dev/null
		if [ $? -eq 0 ]; then
			echo "$1 aready exist"
			#rm $1
			return 1
		fi
	done
	return 0
}

function changeName(){
	# Ignore spaces
	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")	

	# Check if file is image
	if file $1 | grep image > /dev/null ; then
		getDateFromIMG $1
	elif file $1 | grep -i media > /dev/null ; then
		getDateFromMOV $1
	else
		echo "Probably specyfied file ($1) is not image or video clip"
		return 2
	fi

	if [[ ! $fdate ]] || [[ ! $ftime ]] || [[ ! $fextension ]]; then
		echo "Probably specified file ($1) has no EXIF fdate available. Exiting ..."
		return 2
	else
		EXISTINGARRAY=(`ls $fdate\ $ftime* 2> /dev/null`)
		#echo ${EXISTINGARRAY[*]}
		
		suffix=$(printf "%04d" ${#EXISTINGARRAY[*]})
		checkDiff $1 || return 3
		copyOrMove $1
		# case $counter in
		# 	0)
		# 		suffix=`printf "%04d" $counter`
		# 		copyOrMove $1
		# 		#echo "0 - copy $1 ---> $fdate\ $ftime$counter.$fextension"
		# 	;;
		# 	1)
		# 		checkDiff $1 || return 3
		# 		#mv --backup=t $fdate\ $ftime.$fextension $fdate\ $ftime-0.$fextension
		# 		counter="-$counter"
		# 		#echo "1 - copy $1 ---> $fdate\ $ftime$counter.$fextension"				
		# 		copyOrMove $1
				
		# 	;;
		# 	*)
		# 		checkDiff $1 || return 3
		# 		counter="-$counter"
		# 		#echo "2+ - copy $1 ---> $fdate\ $ftime$counter.$fextension"				
		# 		copyOrMove $1
		# 	;;
		# esac
	fi
	# Bring back default IFS
	IFS=$SAVEIFS
}

function help(){
	echo -e "Usage:\n\tnameIT IMG1.jpg IMG2.jpg\n\tnameIT --cp IMG1.jpg IMG2.jpg\nHint:\n\tnameIT *.[Jj][pP][gG]"
}

function main(){
	checkDepends
	# Merge all parameters with \ in one
	for args in "$@"
	do
		if [[  $args == "--save" ]] || [[ $args == "--cp" ]] ;then
			continue
		else
			changeName "$args" 
		fi
	done
}

case $1 in
	--help|-h)
		help
	;;
	"")
		help
	;;
	--save|--cp)
		save=1
		main "$@"
	;;
	*)
		save=0
		main "$@"
		#echo $?
	;;
esac

